import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import PdfPrinter from "pdfmake";
import { TDocumentDefinitions } from "pdfmake/interfaces";

const fonts = {
  Helvetica: {
    normal:      "Helvetica",
    bold:        "Helvetica-Bold",
    italics:     "Helvetica-Oblique",
    bolditalics: "Helvetica-BoldOblique",
  },
};

function fmt(n: number | string) {
  return `RM ${Number(n).toFixed(2)}`;
}

export async function GET(req: NextRequest, { params }: { params: { id: string } }) {
  const session = await getServerSession(authOptions);
  if (!session?.user) return NextResponse.json({ error: "Unauthenticated" }, { status: 401 });

  const order = await prisma.deliveryOrder.findUnique({
    where: { id: params.id },
    include: {
      fromClinic: { select: { name: true, entity: { select: { legalName: true } } } },
      toClinic:   { select: { name: true, entity: { select: { legalName: true } } } },
      raisedBy:   { select: { name: true } },
      approvedBy: { select: { name: true } },
      poolOrder:  { select: { poRef: true } },
      lines: {
        include: { item: { select: { name: true, sku: true, unit: true } } },
      },
    },
  });

  if (!order) return NextResponse.json({ error: "Not found" }, { status: 404 });

  const totalValue = order.lines.reduce(
    (s, l) => s + (l.receivedQty ?? l.quantity) * Number(l.unitCost), 0
  );

  const lineRows = order.lines.map((l) => {
    const qty = l.receivedQty ?? l.quantity;
    return [
      { text: l.item.name, fontSize: 9 },
      { text: l.item.sku,  fontSize: 9, color: "#6b7280" },
      { text: `${l.quantity} ${l.item.unit}`, fontSize: 9, alignment: "center" as const },
      { text: l.receivedQty !== null ? `${l.receivedQty} ${l.item.unit}` : "—", fontSize: 9, alignment: "center" as const,
        color: l.receivedQty !== null && l.receivedQty !== l.quantity ? "#d97706" : "#111827" },
      { text: fmt(l.unitCost), fontSize: 9, alignment: "right" as const },
      { text: fmt(qty * Number(l.unitCost)), fontSize: 9, alignment: "right" as const, bold: true },
    ];
  });

  const statusBadge = (s: string) =>
    ({ DRAFT: "Draft", PENDING: "Pending", APPROVED: "Approved",
       IN_TRANSIT: "In Transit", RECEIVED: "Received", INVOICED: "Invoiced" })[s] ?? s;

  const docDef: TDocumentDefinitions = {
    defaultStyle: { font: "Helvetica", fontSize: 10 },
    pageSize: "A4",
    pageMargins: [40, 40, 40, 60],

    footer: (currentPage, pageCount) => ({
      margin: [40, 0],
      columns: [
        { text: `Generated by DentalOS · ${new Date().toLocaleDateString("en-MY")}`, color: "#9ca3af", fontSize: 8 },
        { text: `Page ${currentPage} of ${pageCount}`, alignment: "right", color: "#9ca3af", fontSize: 8 },
      ],
    }),

    content: [
      // ── Header ────────────────────────────────────────────────────────
      {
        columns: [
          {
            stack: [
              { text: "DentalOS", fontSize: 20, bold: true, color: "#1d4ed8" },
              { text: order.fromClinic.entity.legalName, fontSize: 9, color: "#6b7280", margin: [0, 2, 0, 0] },
            ],
          },
          {
            stack: [
              { text: "DELIVERY ORDER", fontSize: 16, bold: true, alignment: "right", color: "#111827" },
              { text: order.doRef, fontSize: 11, alignment: "right", color: "#374151", margin: [0, 4, 0, 0] },
              {
                text: statusBadge(order.status),
                alignment: "right",
                fontSize: 9,
                bold: true,
                color: order.status === "RECEIVED" ? "#059669" : order.status === "IN_TRANSIT" ? "#4338ca" : "#374151",
                margin: [0, 2, 0, 0],
              },
            ],
          },
        ],
        margin: [0, 0, 0, 20],
      },

      // divider
      { canvas: [{ type: "line", x1: 0, y1: 0, x2: 515, y2: 0, lineWidth: 1, lineColor: "#e5e7eb" }], margin: [0, 0, 0, 16] },

      // ── From / To ─────────────────────────────────────────────────────
      {
        columns: [
          {
            stack: [
              { text: "FROM", fontSize: 8, bold: true, color: "#9ca3af", letterSpacing: 1 },
              { text: order.fromClinic.name, fontSize: 11, bold: true, margin: [0, 4, 0, 0] },
              { text: order.fromClinic.entity.legalName, fontSize: 9, color: "#6b7280" },
            ],
          },
          {
            stack: [
              { text: "TO", fontSize: 8, bold: true, color: "#9ca3af", letterSpacing: 1 },
              { text: order.toClinic.name, fontSize: 11, bold: true, margin: [0, 4, 0, 0] },
              { text: order.toClinic.entity.legalName, fontSize: 9, color: "#6b7280" },
            ],
          },
          {
            stack: [
              { text: "DETAILS", fontSize: 8, bold: true, color: "#9ca3af", letterSpacing: 1 },
              ...(order.raisedBy    ? [{ text: `Raised by: ${order.raisedBy.name}`, fontSize: 9, margin: [0, 4, 0, 0] }] : []),
              ...(order.approvedBy  ? [{ text: `Approved by: ${order.approvedBy.name}`, fontSize: 9 }] : []),
              ...(order.dispatchedAt ? [{ text: `Dispatched: ${new Date(order.dispatchedAt).toLocaleDateString("en-MY")}`, fontSize: 9 }] : []),
              ...(order.receivedAt  ? [{ text: `Received: ${new Date(order.receivedAt).toLocaleDateString("en-MY")}`, fontSize: 9 }] : []),
              ...(order.poolOrder   ? [{ text: `Pool Order: ${order.poolOrder.poRef}`, fontSize: 9, color: "#4338ca" }] : []),
            ],
          },
        ],
        margin: [0, 0, 0, 24],
      },

      // ── Notes ─────────────────────────────────────────────────────────
      ...(order.notes ? [{
        table: {
          widths: ["*"],
          body: [[{ text: `Note: ${order.notes}`, fontSize: 9, color: "#374151", fillColor: "#f9fafb", margin: [8, 6, 8, 6] }]],
        },
        layout: { hLineColor: () => "#e5e7eb", vLineColor: () => "#e5e7eb" },
        margin: [0, 0, 0, 16],
      }] : []),

      // ── Items table ───────────────────────────────────────────────────
      {
        table: {
          headerRows: 1,
          widths: ["*", 70, 65, 65, 65, 70],
          body: [
            // header row
            [
              { text: "Item",             style: "tableHeader" },
              { text: "SKU",              style: "tableHeader" },
              { text: "Dispatched",       style: "tableHeader", alignment: "center" as const },
              { text: "Received",         style: "tableHeader", alignment: "center" as const },
              { text: "Unit Cost",        style: "tableHeader", alignment: "right"  as const },
              { text: "Line Total",       style: "tableHeader", alignment: "right"  as const },
            ],
            ...lineRows,
          ],
        },
        layout: {
          hLineColor: (i: number) => i === 0 || i === 1 ? "#374151" : "#f3f4f6",
          vLineColor: () => "#f3f4f6",
          fillColor: (i: number) => i % 2 === 0 && i > 0 ? "#f9fafb" : null,
        },
        margin: [0, 0, 0, 0],
      },

      // ── Total ─────────────────────────────────────────────────────────
      {
        columns: [
          { text: "", width: "*" },
          {
            table: {
              widths: [120, 80],
              body: [
                [
                  { text: "Total Value", bold: true, fontSize: 10, margin: [8, 6, 8, 6] },
                  { text: fmt(totalValue), bold: true, fontSize: 11, alignment: "right", margin: [0, 6, 8, 6], color: "#1d4ed8" },
                ],
              ],
            },
            layout: { hLineColor: () => "#1d4ed8", vLineColor: () => "#1d4ed8" },
          },
        ],
        margin: [0, 8, 0, 32],
      },

      // ── Signature lines ────────────────────────────────────────────────
      {
        columns: [
          {
            stack: [
              { canvas: [{ type: "line", x1: 0, y1: 0, x2: 160, y2: 0, lineWidth: 1, lineColor: "#374151" }] },
              { text: "Prepared / Dispatched by", fontSize: 8, color: "#6b7280", margin: [0, 4, 0, 0] },
              { text: order.fromClinic.name, fontSize: 8, color: "#9ca3af" },
            ],
          },
          { text: "", width: "*" },
          {
            stack: [
              { canvas: [{ type: "line", x1: 0, y1: 0, x2: 160, y2: 0, lineWidth: 1, lineColor: "#374151" }] },
              { text: "Received by", fontSize: 8, color: "#6b7280", margin: [0, 4, 0, 0] },
              { text: order.toClinic.name, fontSize: 8, color: "#9ca3af" },
            ],
          },
        ],
      },
    ],

    styles: {
      tableHeader: {
        bold: true,
        fontSize: 8,
        color: "#ffffff",
        fillColor: "#1e3a5f",
        margin: [4, 6, 4, 6],
      },
    },
  };

  const printer = new PdfPrinter(fonts);
  const pdfDoc = printer.createPdfKitDocument(docDef);

  const chunks: Buffer[] = [];
  pdfDoc.on("data", (chunk: Buffer) => chunks.push(chunk));

  const pdfBuffer = await new Promise<Buffer>((resolve, reject) => {
    pdfDoc.on("end",   () => resolve(Buffer.concat(chunks)));
    pdfDoc.on("error", reject);
    pdfDoc.end();
  });

  return new NextResponse(pdfBuffer, {
    status: 200,
    headers: {
      "Content-Type":        "application/pdf",
      "Content-Disposition": `inline; filename="DO-${order.doRef}.pdf"`,
    },
  });
}
